### ISSUE TITLE
下载的Demo引用的'com.github.angcyo:DslAdapter:6.0.2'失效了吗？

### ISSUE THREAD

**Issue by MrRongHuang** [angcyo/DslTabLayout#106]

**Comment by angcyo** [comment]
可以在此查看库的状态: https://jitpack.io/#angcyo/DslAdapter

显示的是正常的.

**Comment by MrRongHuang** [comment]
查看库的状态是没有问题，就是在demo上面，编译项目的时候，拉取失效了，我这边在几个同事的电脑上面看了，也是一样的问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "angcyo/DslTabLayout"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月23日(星期二) 上午9:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [angcyo/DslTabLayout] 下载的Demo引用的'com.github.angcyo:DslAdapter:6.0.2'失效了吗？ (Issue #106)





 
可以在此查看库的状态: https://jitpack.io/#angcyo/DslAdapter
 
显示的是正常的.
