### ISSUE TITLE
observeIndexChange问题

### ISSUE THREAD

**Issue by pandy23** [angcyo/DslTabLayout#109]
我只是想简单的监听选中tab后消除角标。

但是代码中不监听observeIndexChange没问题，写了该方法以后（方法里啥也写），选中tab不能自动切换viewpage了，左右滑动也会出现错乱的问题。

所以还需要在这个方法里做什么其他操作吗？

**Comment by angcyo** [comment]
源码`DslTabLayout`192行,有一条注释`//如果设置[tabLayoutConfig?.onSelectIndexChange], 那么会覆盖[_viewPagerDelegate]的操作.`;

所以需要转发一下页面切换操作:

调用`DslTabLayout._viewPagerDelegate?.onSetCurrentItem(fromIndex, toIndex, reselect, fromUser)`;
