### ISSUE TITLE
高凸tab高出的部分没有点击回调

### ISSUE THREAD

**Issue by wy7217** [angcyo/DslTabLayout#11]
这里高凸tab貌似用clipChildren实现 没有点击回调 有什么好的解决方案吗

**Comment by angcyo** [comment]
`高凸`效果的实现, 只是使用了一个`障眼法`. 只控制了`child`的高度差, 和布局的位置.

并非`clip`实现, 所以`点击事件`的处理, 还是系统默认的处理方式. 

请检查自己的代码. 

`Demo`中, `MainFragment`底部导航中间的`高凸Item`亲测是有效的.
