### ISSUE TITLE
大佬，item同时有图片和文字的，内部是默认只修改第一个吗

### ISSUE THREAD

**Issue by fumayer** [angcyo/DslTabLayout#110]
![WX20240814-202055@2x](https://github.com/user-attachments/assets/9d6e4f96-a9d2-44cb-91fb-e0243aaf3c3f)

<com.angcyo.tablayout.DslTabLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/tab_layout"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:background="@color/white"
    android:minHeight="50dp"
    app:tab_deselect_color="@color/text"
    app:tab_indicator_color="@color/colorAccent"
    app:tab_indicator_drawable="@drawable/indicator_bottom_line"
    app:tab_indicator_height="3dp"
    app:tab_item_is_equ_width="true"
    app:tab_select_color="@color/colorAccent"
    tools:tab_default_index="1">
<LinearLayout
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:gravity="center_horizontal"
        android:orientation="vertical">

        <ImageView
            android:layout_width="30dp"
            android:layout_height="30dp"
            android:src="@drawable/shape_round_background_tran_selector_test" />

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="哈哈哈哈" />
    </LinearLayout>
就是这种，我用了LinearLayout，图片用了selector, 显示效果就是选中后图片会切换，但是文字颜色不会变

**Comment by fumayer** [comment]
可是我看xml中只能指定一个id，我怎么让四个都实现 那种效果呢， 是需要在代码中指定id吗？

**Comment by angcyo** [comment]
4个图片控件用同一个id, 4个文本控件用同一个id. 即可.

**Comment by fumayer** [comment]
我用的databinding，xml中没法共用一个id，我再想想其他办法吧，多谢啦

**Comment by angcyo** [comment]
> 我用的databinding，xml中没法共用一个id，我再想想其他办法吧，多谢啦

官方的弃子, 为何还要用?

**Comment by fumayer** [comment]
啊？已经不推荐了吗，我都不知道
