### ISSUE TITLE
大佬,item文本多重颜色我应该怎么弄比较合适

### ISSUE THREAD

**Issue by fumayer** [angcyo/DslTabLayout#112]
![WX20240930-175157@2x](https://github.com/user-attachments/assets/bd4a7938-8d0c-4e9c-bddf-9726dee6c4a2)

外部能否用spannable改变TextView的颜色呢

**Comment by angcyo** [comment]
使用`com.angcyo.tablayout.DslTabLayoutConfig#setTabGradientCallback`属性, 自定义可以解决.

**Comment by fumayer** [comment]
![WX20240930-182759@2x](https://github.com/user-attachments/assets/713063a4-2440-4dea-a555-5af5de76f4a8)
大佬,我这用法是不是有问题,颜色改变后,再切换一直是多重颜色,不变回未选中颜色了
![Uploading WX20240930-183033@2x.png…]()

**Comment by fumayer** [comment]
![WX20240930-183033@2x](https://github.com/user-attachments/assets/b83b3862-d343-4bd9-a419-9b9f8a469857)

**Comment by angcyo** [comment]
思路是对的

**Comment by fumayer** [comment]
大佬,具体明示下呗,多谢多谢
