### ISSUE TITLE
按照官方demo的方法  android:state_selected="true" 选择器设置的图片 不生效

### ISSUE THREAD

**Issue by xiang473535976** [angcyo/DslTabLayout#113]
![image](https://github.com/user-attachments/assets/1af3306e-e356-4f62-858c-824d3b9590b1)
![image](https://github.com/user-attachments/assets/f456f57d-1128-4e97-aa27-1928dba48366)
![Screenshot_2024-10-16-13-47-24-511_com angcyo dsltablayout demo](https://github.com/user-attachments/assets/423c1781-0af7-4cd6-b33c-e8d7f5376c5d)

官方demo，这样设子的图片不生效，被tab_select_color设置的颜色覆盖了  请大佬看看

**Comment by angcyo** [comment]
用`ViewGroup`包裹起来,然后自定义处理.

**Comment by xiang473535976** [comment]
> 用`ViewGroup`包裹起来,然后自定义处理.

请问怎么自定义   谢谢

**Comment by xiang473535976** [comment]
需要配置 app:tab_enable_ico_color="false"       app:tab_enable_text_color="false"  这两个就行了  谢谢大佬
