### ISSUE TITLE
动态修改tab_border_solid_color

### ISSUE THREAD

**Issue by yxiangTang** [angcyo/DslTabLayout#114]
大佬，想问一下现在有支持动态设置tab_border_solid_color的值吗，我目前尝试了设置tabBorder.gradientSolidColor和tabBorder.borderItemBackgroundSolidColor都不生效，invalidate都不行。

尝试了设置完tabBorder.gradientSolidColor和tabBorder.borderItemBackgroundSolidColor后，再调用updateOriginDrawable()，背景色倒是变了，但是指示器和tabItem都看不见了。求指点！！

**Comment by yxiangTang** [comment]
曲线救国，用tabBorder?.borderBackgroundDrawable?.setTint(color)就解决了

**Comment by angcyo** [comment]
方便写个`demo`?

**Comment by yxiangTang** [comment]
这里

**Comment by yxiangTang** [comment]
[DslTabLayoutDemo.zip](https://github.com/user-attachments/files/17489430/DslTabLayoutDemo.zip)
