### ISSUE TITLE
激活文本渐变下，点击切换时文本颜色不能正常恢复

### ISSUE THREAD

**Issue by SmallWinter** [angcyo/DslTabLayout#13]
首先感谢作者，目前看来这个库很强大，有望成为下一个热点。
library版本：V1.5.2，用的viewpager2。
使用时所有属性都在layout里面设置，开启 tab_enable_gradient_color = true 之后，viewpager滑动切换tab无问题；但是当点击切换tab时，被点击tab未能达到预设颜色，会比预设颜色暗一些（个人猜测：可能是点击未处理好颜色的切换问题）。然后再滑动viewpager2就正常，或者说稍微动一下viewpager2就又正常。

**Comment by angcyo** [comment]
`1.5.3`已修复. 感谢反馈!
