### ISSUE TITLE
自动着色无效

### ISSUE THREAD

**Issue by zwt-ss** [angcyo/DslTabLayout#14]
<attr name="tab_select_color" format="color" />

<attr name="tab_deselect_color" format="color" />

<attr name="tab_ico_select_color" format="color" />

<attr name="tab_ico_deselect_color" format="color" />

这几个属性对imageview不生效，只对文字有效，指示器也没有显示
这是我的xml
        <com.angcyo.tablayout.DslTabLayout
            android:id="@+id/dslTabLayout"
            android:layout_width="match_parent"
            android:layout_height="48dp"
            app:layout_constraintBottom_toBottomOf="parent"
            app:tab_draw_indicator="true"
            app:tab_indicator_color="@color/colorPrimary"
            app:tab_item_is_equ_width="true"
            app:tab_select_color="@color/colorPrimary"
            app:tab_deselect_color="#626262">

**Comment by angcyo** [comment]
`tab_indicator_color`属性是给`tab_indicator_drawable`属性指定的`Drawable`着色.

如果要设置纯色指示器,请使用`tab_indicator_solid_color`.
纯色渐变指示器`tab_indicator_gradient_start_color` `tab_indicator_gradient_end_color`.

默认`tab_select_color` `tab_deselect_color` 只处理`TextView`, 如果要支持`ImageView`
请调用`com.angcyo.tablayout.DslTabLayout#configTabLayoutConfig`方法, 重写`onGetIcoStyleView`属性, 返回想要变色的`ImageView`即可.
