### ISSUE TITLE
角标属性

### ISSUE THREAD

**Issue by 330676687** [angcyo/DslTabLayout#17]
角标可以加个边框颜色和粗细的属性吗

**Comment by angcyo** [comment]
`1.5.6` 更新:

 `TabBadgeConfig`新增了以下属性:

```kotlin
data class TabBadgeConfig(
   ...

    /**角标边框颜色*/
    var badgeStrokeColor: Int = Color.TRANSPARENT,
    /**角标边框宽度*/
    var badgeStrokeWidth: Int = 0

  ...
```

**Comment by 330676687** [comment]
是不是忘了在DslBadgeDrawable这个类更新了，无法通过onTabBadgeConfig直接设置

**Comment by angcyo** [comment]
> 是不是忘了在DslBadgeDrawable这个类更新了，无法通过onTabBadgeConfig直接设置

可以通过`DslTabBadge`对象的 `gradientStrokeColor` `gradientStrokeWidth`属性达到相同效果.
