### ISSUE TITLE
动态添加的item，怎么设置indicator和文字的宽度一样？java项目

### ISSUE THREAD

**Issue by zaaach** [angcyo/DslTabLayout#19]
kotlin看不明白=.=

**Comment by angcyo** [comment]
情况1:
直接使用`TextView`当做Item, 则将指示器的`indicatorWidth` 或 xml属性`tab_indicator_width` 设置为`-2` 即可. 此时的宽度, 就是文字的宽度(去除了padding)

情况2:
使用`ViewGroup`嵌套`TextView`当做Item, 则需要在`ViewGroup`的`LayoutParams`中指定`TextView`在`ViewGroup`中的索引值, 设置给变量`indicatorContentIndex`, 其余配置和`情况1`一致.
