### ISSUE TITLE
大神，可以支持viewpager2吗

### ISSUE THREAD

**Issue by dragon-y** [angcyo/DslTabLayout#2]

**Comment by angcyo** [comment]
已兼容`ViewPager2`

https://github.com/angcyo/DslTabLayout/wiki/ViewPager1%E5%92%8CViewPager2

**Comment by dragon-y** [comment]
感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"angcyo"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月14日(星期六) 晚上10:36
收件人:&nbsp;"angcyo/DslTabLayout"<DslTabLayout@noreply.github.com&gt;;
抄送:&nbsp;"11621546"<11621546@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [angcyo/DslTabLayout] 大神，可以支持viewpager2吗 (#2)




Closed #2.
