### ISSUE TITLE
请问大佬, java代码动态设置一些属性, 目前是不是不支持???

### ISSUE THREAD

**Issue by harryhasai** [angcyo/DslTabLayout#20]
![image](https://user-images.githubusercontent.com/28555314/90006022-b700aa00-dcca-11ea-8d1b-b3f1a8999b20.png)
如图, 由于项目里需要修改字体大小, 所以这里可能要动态修改一些放大或者缩小字体,

**Comment by angcyo** [comment]
[参考文档](https://github.com/angcyo/DslTabLayout/wiki/%E7%94%A8%E4%BB%A3%E7%A0%81%E6%8E%A7%E5%88%B6%E6%A0%B7%E5%BC%8F)
