### ISSUE TITLE
怎么设置itme之间的分割线

### ISSUE THREAD

**Issue by bonjourss** [angcyo/DslTabLayout#21]

**Comment by bonjourss** [comment]
border / divider 都试了还是不显示

**Comment by bonjourss** [comment]
app:tab_draw_divider="true"
        app:tab_divider_width="@dimen/dp_px_1"
        app:tab_divider_solid_color="@color/divider"
        app:tab_divider_margin_top="@dimen/dp_px_17"
        app:tab_divider_margin_bottom="@dimen/dp_px_13"

(⊙﹏⊙)刚问完就可以了

**Comment by angcyo** [comment]
> ```
>     app:tab_draw_divider="true"
>     app:tab_divider_width="@dimen/dp_px_1"
>     app:tab_divider_solid_color="@color/divider"
>     app:tab_divider_margin_top="@dimen/dp_px_17"
>     app:tab_divider_margin_bottom="@dimen/dp_px_13"
> ```
> 
> (⊙﹏⊙)刚问完就可以了

哈哈!
