### ISSUE TITLE
动画功能增强请求

### ISSUE THREAD

**Issue by oh-Rin** [angcyo/DslTabLayout#22]
DslTabLayout 能做到这种效果吗，或者说有没有什么接口可以快速实现
https://github.com/Ultrahuman-tech/SmartTabLayout
![image](https://raw.githubusercontent.com/ogaclejapan/SmartTabLayout/master/art/demo4.gif)

**Comment by angcyo** [comment]
可以试试 激活属性`indicatorEnableFlow`或者xml`tab_indicator_enable_flow`

如果还不满足, 继承 `DslTabIndicator`, 重写`draw`方法.  将`dslTabLayout.tabIndicator`成员替换成自定义的对象
