### ISSUE TITLE
我这边选中和未选中的颜色属性失效

### ISSUE THREAD

**Issue by AndMy** [angcyo/DslTabLayout#23]
app:tab_select_color="#F42834"
app:tab_deselect_color="@color/c6"
用下面的代码设置也是没效果的
onSelectIndexChange = { fromIndex, selectIndexList, reselect,_ ->
                val toIndex = selectIndexList.first()
                tabSelectColor = Color.parseColor("#F42834")
                tabDeselectColor = Color.parseColor("#666666")
                _viewPagerDelegate?.onSetCurrentItem(fromIndex, selectIndexList.last())
            }
能帮我看一下什么问题？

**Comment by AndMy** [comment]
可以了，我在textview外面嵌套了一层ConstraintLayout布局，item布局必须是textview？

**Comment by angcyo** [comment]
> 可以了，我在textview外面嵌套了一层ConstraintLayout布局，item布局必须是textview？

不是必须的. 

可以通过`configTabLayoutConfig`指定`TextView`控件的id. 属性名:tabTextViewId

**Comment by scsfwgy** [comment]
懂了。感谢。
