### ISSUE TITLE
在配置TabLayout不等宽的时候, 滑动Tab会出现文字抖动的现象

### ISSUE THREAD

**Issue by harryhasai** [angcyo/DslTabLayout#25]
我这里的是在TabLayout里动态添加了3个TextView, 同时这是了tab_selected_text_size和tab_unSelected_text_size, 还有text_seleced_bold, 发现在屏幕等宽模式下, 切换一切正常, 但是在不等宽的时候, 切换Tab会出现文字抖动的情况, TextView的左右内边距我设置的是15dp. 我有2出地方是这么写的, 其中一处用的是ViewPager 这个没发现有这个问题, 但是另外一处用的是viewPager2, 就出现这个问题,

**Comment by harryhasai** [comment]
另外 , 用ViewPager那里布局不是动态的, 是写死的, 直接在布局文件里添加的TextView, 同时用的是ViewPager, 这里就是一切正常..目前还没有发现问题到底出在哪里

**Comment by angcyo** [comment]
text size 会影响控件的 width, 导致抖动.
请使用性能更好的scale属性.
