### ISSUE TITLE
drawBadge 在kotlin代码中设置无效，但是在xml中可以

### ISSUE THREAD

**Issue by WayneSimon** [angcyo/DslTabLayout#27]
![image](https://user-images.githubusercontent.com/20898551/95650223-d07c7180-0b14-11eb-8e93-1fce06f2c944.png)
集合Viewpager2使用的，代码如下
dslTab.apply {
                drawIndicator = false//不绘制指示器
                itemAutoEquWidth = true//平均分配总宽度
                drawBadge = true//是否绘制角标,必须去xml里面配置，这里经常失效
            }

**Comment by angcyo** [comment]
如果`drawBadge`是从`false`切换到`true`,
还需要给`tabBorder`赋值`DslTabBorder()`.

```
drawBadge=true
tabBorder=DslTabBorder()
```
