### ISSUE TITLE
库是好库，我这种渣渣看不懂你写的Demo，跪了

### ISSUE THREAD

**Issue by ximenchuipaopao** [angcyo/DslTabLayout#28]

**Comment by angcyo** [comment]
`kotlin`+`dsl`入门指南

**Comment by 838239178** [comment]
我曾经绞尽脑汁想要写出这个库里面的一个效果 结果捣鼓不出来 今天github推给我这个 解了心中大石头

**Comment by angcyo** [comment]
> 我曾经绞尽脑汁想要写出这个库里面的一个效果 结果捣鼓不出来 今天github推给我这个 解了心中大石头

什么效果让你如饥似渴？

**Comment by 838239178** [comment]
> 什么效果让你如饥似渴？

taptap同款粘滞效果的indicator😍

**Comment by angcyo** [comment]
> > 什么效果让你如饥似渴？
> 
> taptap同款粘滞效果的indicator😍

爱奇艺也是这种效果，很常见。

**Comment by LiWeiQiangAndroid** [comment]
竖向时，图标文字可以上下结构？

**Comment by angcyo** [comment]
可以.
