### ISSUE TITLE
内部加个HorizontalScrollView做成可滑动的要怎么搞？

### ISSUE THREAD

**Issue by cbuemc** [angcyo/DslTabLayout#3]
现在有个需求，要做成内部可以滑动，我太难了

**Comment by angcyo** [comment]
`DslTabLayout` 支持智能横向滑动.

**Comment by cbuemc** [comment]
> `DslTabLayout` 支持智能横向滑动.

我要的是内部滑动，外面的框是固定的，内部的标题和选中背景可以左右滑动

**Comment by angcyo** [comment]
什么场景? 有GIF效果?

**Comment by cbuemc** [comment]
> 什么场景? 有GIF效果?

我自己加了个HorizontalScrollView搞定了
