### ISSUE TITLE
等分时，怎样设置指示器宽度等于文字宽度

### ISSUE THREAD

**Issue by liu-xinhui** [angcyo/DslTabLayout#31]
![image](https://user-images.githubusercontent.com/7698511/102198836-d5d3af00-3efd-11eb-83de-3e68235754dd.png)
![image](https://user-images.githubusercontent.com/7698511/102198856-dcfabd00-3efd-11eb-9031-db6ae2d5b2e5.png)
现在底部指示线宽度等于文本框宽度了，我想要等于文字宽度

**Comment by angcyo** [comment]
1:指示器的宽度使用'wrap_content'
2:`item`中的`textView`用`ViewGroup`包裹一层
3:使用`tab_indicator_content_index`属性定位`textView`

**Comment by NicodeLee** [comment]
每一层item包裹一层挺麻烦的
