### ISSUE TITLE
设置分割线，超过4个item的时候，最后一个选中的背景不能铺满，看图

### ISSUE THREAD

**Issue by Alexxiaopang** [angcyo/DslTabLayout#32]
![1609237200(1)](https://user-images.githubusercontent.com/13740721/103276873-9f6c5880-4a02-11eb-8c3c-dac3b4990675.jpg)

可看demo的截图，只在demo中增添了两个item

**Comment by angcyo** [comment]
调整首尾item的宽度大小, 达到效果为止.

暂时没有其他很好的解决方法.
