### ISSUE TITLE
现在仍然不支持给item设置默认背景？

### ISSUE THREAD

**Issue by liuxuebing2010** [angcyo/DslTabLayout#36]
不能实现这种效果？
![image](https://user-images.githubusercontent.com/18303869/111407900-61342a80-870f-11eb-8db5-9f630924a8b3.png)

**Comment by angcyo** [comment]
支持啊!

1: 通过`tab_draw_indicator=false`关闭默认的指示器.
2: `item`的`background`通过`android:state_selected="true"`状态设置选中时的效果.
