### ISSUE TITLE
指定滑动到超出屏幕宽度的index的位置时，tablayout没有滑动使选中的item显示在屏幕上

### ISSUE THREAD

**Issue by uncleShi** [angcyo/DslTabLayout#37]
使用  mTabLayout.setCurrentItem(index); 方法指定滑动到超出屏幕的某个位置时，item被选中了，但是tablayout内部没有滑动到选中的位置使其显示在屏幕上

**Comment by angcyo** [comment]
`2.0.2`已修复, 感谢反馈!

**Comment by uncleShi** [comment]
> `2.0.2`已修复, 感谢反馈!

这个是我在使用1.5.1-support版本中发现的，作者后续是否会继续发布support版本呢？

**Comment by angcyo** [comment]
已兼容 `2.0.2-support`
