### ISSUE TITLE
请问一下关于多语言适配的问题

### ISSUE THREAD

**Issue by yunnec** [angcyo/DslTabLayout#4]
如果是像阿拉伯语这种需要左右颠倒的语言，需要怎样做比较好？动态添加TextView然后改变数据源吗

**Comment by angcyo** [comment]
抱歉, 还没考虑到需要支持`RTL`的情况!

你可以把`UI设计`和`需求`给我看下么?

目前你可以用动态`addView`的形式达到效果.

**Comment by show1hand** [comment]
<img width="356" alt="WX20191224-104636@2x" src="https://user-images.githubusercontent.com/28297534/71390437-5c331900-263b-11ea-8b45-009f5240088f.png">
不太方面直接传UI，基本是这个样子的，上下两个tablayout，其中二级tablayout的item会比较多，具体数量是从服务端获取的。比较关键的点是要支持RTL。

**Comment by angcyo** [comment]
上述布局 要变成
TAB1-3 TAB1-2 TAB1-1
TAB2-4 TAB2-3 TAB2-2 TAB2-1

然后其他代码不变, 只是单纯的`RTL`布局方式?

**Comment by show1hand** [comment]
我这边index可能不太用的到，因为比较紧急，我先使用RTL情况下切换数据源的方式来实现了。能支持index的话还是更好一些。

**Comment by XiongKe94** [comment]
@angcyo 能不能扩展布局从右到左方向如图。
![屏幕快照 2020-12-23 16 21 35](https://user-images.githubusercontent.com/19948815/102975495-26b95800-453b-11eb-86c7-66307ca50f4c.png)
![屏幕快照 2020-12-23 16 22 07](https://user-images.githubusercontent.com/19948815/102975504-291bb200-453b-11eb-851d-095ebc66597c.png)

**Comment by scsfwgy** [comment]
需求+1，应用需要支持阿拉伯语。基本可以理解为正常用户布局的镜像。就是对Rtl的支持。

**Comment by scsfwgy** [comment]
这个东西理论上不是通过改变数据源方式进行支持的。像原生控件，TextView,ViewGroup默认都是支持的，只要语言跳转为阿拉伯语，UI自动镜像。

**Comment by angcyo** [comment]
> 需求+1，应用需要支持阿拉伯语。基本可以理解为正常用户布局的镜像。就是对Rtl的支持。

如果布局支持`RTL`, 那滚动方向是不是和`LTR`反过来了?

比如: `LTR`时, 滚动有效值是`0~1000`, 但是`RTL`时, 滚动有效值就是`-1000~0`? 是这样的么?

**Comment by scsfwgy** [comment]
应该不是吧。你看一下LinearLayout的源码，他就是把索引currIndex=count-1,换句话说就是tab的tab第一个跑到了最后一个，反转过来。其他应该不动。android-29 LinearLayout line:1750。点击事件：最后一个index成了第一个。


![image](https://user-images.githubusercontent.com/16045179/124885332-bde08b80-e005-11eb-931f-39e1bf0bb232.png)

**Comment by angcyo** [comment]
`LinearLayout`不涉及滚动, 只具备布局的参考价值.

看了下`HorizontalScrollView`的代码, 发现滚动也是反过来的.

**Comment by angcyo** [comment]
`3.0.0` 后, 支持`RTL`.

> 注意: `Demo`中使用的是系统`ViewPager`, 默认是不支持`RTL`的.

可以参考以下库:
https://github.com/diego-gomez-olvera/RtlViewPager
