### ISSUE TITLE
类似于这种效果能实现吗

### ISSUE THREAD

**Issue by yxyaxng** [angcyo/DslTabLayout#40]
![微信截图_20210514220043](https://user-images.githubusercontent.com/24906252/118281538-e6fe0780-b4ff-11eb-9be1-88d690ba4c0d.png)

**Comment by angcyo** [comment]
`黄色背景图片`设置给`DslTabLayout`的`android:background`属性.

`白色选中图片`设置给`item`选择器中的`state_selected`属性.
