### ISSUE TITLE
tab_text_view_id 指定View

### ISSUE THREAD

**Issue by Yanzhishang** [angcyo/DslTabLayout#42]
tab_text_view_id 属性设置多个 TextView,TextView 相同 ID 无法编译，请问如何做到的

**Comment by Yanzhishang** [comment]
demo 里是可以 的，但是我的xml却不行 无法编译

**Comment by angcyo** [comment]
试试在`app`module的`build.gradle`文件中加入:

```
android {

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    /*kotlinOptions { jvmTarget = "1.8" }*/
    kotlinOptions { jvmTarget = JavaVersion.VERSION_1_8 }
}
```

**Comment by ujffdi** [comment]
gradle 7.0+加里也无法通过编译。另外想实现开眼app首页底部tab的效果，大概怎么做？切换的动画已实现。打算使用相同id找到view播放动画，可是无法编译

**Comment by ujffdi** [comment]
gradle 7.0+加里也无法通过编译。另外想实现开眼app首页底部tab的效果，大概怎么做？切换的动画已实现。打算使用相同id找到view播放动画，可是无法编译

**Comment by angcyo** [comment]
源码已更新AGP至`7.4.2`

`开眼 Eyepetizer - 精品短视频`底部导航很常规的设计, 库可以实现.不难!
