### ISSUE TITLE
DslTabLayout#currentItemIndex 为什么会取到-1？

### ISSUE THREAD

**Issue by scsfwgy** [angcyo/DslTabLayout#44]
DslTabLayout#currentItemIndex判断获取到对应的索引，结果获取到了-1。非必现。

**Comment by angcyo** [comment]
在首次布局未完成时, 就有可能获取到-1.

请等待布局结束之后, 再获取.

**Comment by scsfwgy** [comment]
这个很奇怪，用户都看到UI了。去点击按钮没反应（我是判定index<0直接终止逻辑的）。不对，根据用户反馈的视频看，一直点击都没反应，切换一下tab就好了，也就是说默认index一直是-1。

**Comment by angcyo** [comment]
有个属性可以设置默认的index, 获取手动调用一次`setCurrentItem`

**Comment by scsfwgy** [comment]
ok
