### ISSUE TITLE
角标，指示器不显示

### ISSUE THREAD

**Issue by CuiGuanFeng** [angcyo/DslTabLayout#45]
<com.angcyo.tablayout.DslTabLayout
        android:id="@+id/dslTabLayout"
        android:layout_width="match_parent"
        android:layout_height="50dp"
        android:layout_gravity="center_vertical"
        android:background="#00000000"
        app:tab_draw_badge="true"
        app:tab_badge_gravity="center"
        app:tab_badge_offset_x="50dp"
        app:tab_badge_offset_y="-10dp"
        app:tab_badge_solid_color="@color/color_EF393B"
        app:tab_badge_text="99"
        app:tab_badge_text_color="@color/white"
        app:tab_badge_text_size="15sp"
        app:tab_deselect_color="@color/color_333333"
        app:tab_draw_indicator="true"
        app:tab_indicator_color="@color/color_4975EC"
        app:tab_indicator_height="1dp"
        app:tab_indicator_style="STYLE_BOTTOM"
        app:tab_indicator_width="MATCH_PARENT"
        app:tab_orientation="HORIZONTAL"
        app:tab_select_color="@color/color_4975EC">
    </com.angcyo.tablayout.DslTabLayout>
    
    
   通过addView添加，角标、指示器不显示
   titles!!.add("地下埋设管道")
                    titles!!.add("地下穿越管道")
                    titles!!.add("架空管(桥管)")
                    titles!!.add("立管")
                    titles!!.add("法兰阀门")
                    titles!!.add("PE阀门")
                    titles!!.add("直埋焊接阀门")
                    titles!!.add("调压柜")
                    titles!!.add("调压箱")
                    titles!!.add("调压室")
                    titles!!.add("牺牲阳极")
              
                    for (s in titles) {
                       
                        binding.dslTabLayout.addView(TextView(this).apply {
                            text = s
                            textSize = 14f
                            gravity = Gravity.CENTER_VERTICAL
                            layoutParams = DslTabLayout.LayoutParams(-2, -2).apply {
                                leftMargin = 20
                                rightMargin = 20
                            }
                        })

                    }

**Comment by angcyo** [comment]
`xml`中配置的角标, 只有在预览的时候才生效.

角标配置请使用方法:`com.angcyo.tablayout.DslTabLayout#updateTabBadge`

**Comment by CuiGuanFeng** [comment]
指示器呢？指示器也不显示

**Comment by angcyo** [comment]
多参考一下`Demo`的代码, 或者 复制粘贴过去, 在此基础上修改.
