### ISSUE TITLE
xml 设置scale字体显示不全，如图

### ISSUE THREAD

**Issue by v1ncent9527** [angcyo/DslTabLayout#48]
![06B98305-EF69-4B45-BA72-EA923F93DB15](https://user-images.githubusercontent.com/17847571/133710061-8ad3e84f-0c6e-431f-bb98-cf0e097f8d99.png)

字体textsize为18sp显示不全，改为16sp就可以显示全

**Comment by v1ncent9527** [comment]
选中”职位“tab时右边显示不全
目前的解决办法是加padding

**Comment by v1ncent9527** [comment]
![A0FE4003-A1B6-44C3-831A-EF10DCEB300C](https://user-images.githubusercontent.com/17847571/133713975-dcae2729-660d-4c6e-b5c6-02b889dd69c8.png)

我看您这边也是添加了padding

**Comment by angcyo** [comment]
可以使用`tabTextMinSize/tabTextMaxSize`属性.


如果一定要用`tabMinScale`, 则需要增加`TextView`的宽度, 以容纳放大后需要占用的空间.
