### ISSUE TITLE
遇到了一个非常奇怪的问题

### ISSUE THREAD

**Issue by Linmuge** [angcyo/DslTabLayout#51]
当我的item没有铺满整个屏幕时,dsltablayout是不可滑动的 ,而这是我点击最后一个tab后切换成小窗状态,这时item数量超出了屏幕,是可以滑动的,这时再从小窗切换回全屏状态,dsltablayout不可滑动且把前几个item顶出了屏幕,滑不回来了,具体情况可以看链接里的录屏
https://dl.muge.info/WeChat_20211105214806.mp4

**Comment by angcyo** [comment]
能提供复现示例代码？

**Comment by Linmuge** [comment]
> 能提供复现示例代码？

经测试,下面demo可以复现
https://dl.muge.info/DslTablayoutDemo.zip

**Comment by angcyo** [comment]
感谢反馈, `3.0.2`已修复
