### ISSUE TITLE
configTabLayoutConfig#onSelectItemView 获取索引不对

### ISSUE THREAD

**Issue by scsfwgy** [angcyo/DslTabLayout#52]
麻烦有时间看一下。在回调里面通过DslTabLayout 获取索引获取的是不对的，但是回调的值 `index`是对的。
代码如下，获取索引不对：

`
 desLayout.configTabLayoutConfig {
                    onSelectItemView = { _, index, select, _ ->
                        Log.d("desLayout", "titles2DslTabLayoutChildren: " + select + "," + index)
                        if (select) {
                                //这里获取索引不对。
                                 val currentItemIndex =dslLayout .currentItemIndex
                        }
                        false
                    }
                }

`

**Comment by angcyo** [comment]
当需要选中`ItemView`时, 才会触发此回调.

你可能需要`onSelectViewChange`回调.
