### ISSUE TITLE
从1.5.9升级3.0.3版本出现了部分地方 第一次显示 第一个Tab时，显示不全的问题

### ISSUE THREAD

**Issue by liuhuan8986** [angcyo/DslTabLayout#54]
<com.angcyo.tablayout.DslTabLayout
                android:id="@+id/dsltTabLayout"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginRight="56dp"
                android:background="@color/white"
                android:paddingLeft="17dp"
                android:paddingTop="10dp"
                android:paddingBottom="5dp"
                app:tab_select_color="@color/text_black"
                app:tab_deselect_color="@color/commodity_specification_gray"
                app:tab_draw_indicator="true"
                app:tab_text_min_size="13sp"
                app:tab_text_max_size="14sp"
                />

**Comment by liuhuan8986** [comment]
如果tab_text_min_size 和  tab_text_max_size 是一样的就没事，tab我是动态加的

**Comment by angcyo** [comment]
`3.0.4`已修复
