### ISSUE TITLE
不支持字体选中放大效果吗

### ISSUE THREAD

**Issue by github999999** [angcyo/DslTabLayout#59]
不支持字体选中放大效果吗

**Comment by angcyo** [comment]
支持`文本大小`变化:

- tab_enable_gradient_text_size 开启效果
- tab_text_min_size 未选中时的字体大小
- tab_text_max_size 选中时的字体大小

同时还支持`缩放大小`变化,性能更好:

- tab_enable_gradient_scale 开启效果
- tab_min_scale 未选中时的缩放比例, 默认是1f
- tab_max_scale 选中时的缩放比例, 比如1.2f

**Comment by github999999** [comment]
nice

> 支持`文本大小`变化:
> 
> * tab_enable_gradient_text_size 开启效果
> * tab_text_min_size 未选中时的字体大小
> * tab_text_max_size 选中时的字体大小
> 
> 同时还支持`缩放大小`变化,性能更好:
> 
> * tab_enable_gradient_scale 开启效果
> * tab_min_scale 未选中时的缩放比例, 默认是1f
> * tab_max_scale 选中时的缩放比例, 比如1.2f

nice
