### ISSUE TITLE
初始化自定义布局item异常问题

### ISSUE THREAD

**Issue by SmallWinter** [angcyo/DslTabLayout#64]
自几定义item，如下面视频所示，初始化组件位置不太对，再来回切换就正常了；具体问题点还不敢确定，但盲猜应该是自动缩放或初始化配置有问题。具体问题如下面视频

https://user-images.githubusercontent.com/8638180/164952742-e908f143-281c-41d9-aaf7-d5913440dc21.mp4

**Comment by angcyo** [comment]
请附上初始化的代码!

**Comment by SmallWinter** [comment]
补充，布局；依赖版本：3.2.1
![布局](https://user-images.githubusercontent.com/8638180/164953176-b865f32f-d221-4cc7-8260-c2accbc10216.png)

**Comment by SmallWinter** [comment]
补充，代码配置
![代码配置](https://user-images.githubusercontent.com/8638180/164953242-34c90fc6-14c5-46fe-a043-9bfb0c528ec4.png)

**Comment by angcyo** [comment]
将`item FrameLayout` 的宽度使用 `WRAP_CONTENT` 试一下.

如果还不行, 提供一个demo给我调试一下.

**Comment by SmallWinter** [comment]
好的，我试一试

**Comment by SmallWinter** [comment]
按你说的方法改了，问题依旧存在；提供了一个demo，项目地址：
https://gitee.com/cxck/DslTabLayoutTest.git

**Comment by angcyo** [comment]
由于首次回调的时候, `ImageView`还未计算出宽高, 此时缩放动画的中点计算有误, 导致效果差异.

可以将动画包裹在`doOnPreDraw`扩展方法中执行.

如下图:

![image](https://user-images.githubusercontent.com/6269676/164955172-16fe4525-324c-460e-83be-5b93ff01d39d.png)
