### ISSUE TITLE
tab_item_is_equ_width=true 后 tabIndicator无法做到与文本宽度自适应对齐

### ISSUE THREAD

**Issue by daiwenbo88** [angcyo/DslTabLayout#65]
com.google.android.material:material:1.5.0 中有个
app:tabIndicatorFullWidth="false" 属性 表示tabIndicator的宽度是不填充整个Tab的

有这方面的支持吗
 
目前 使用 tab_item_is_equ_width=true 后 tabIndicator无法做到与文本宽度对齐

**Comment by angcyo** [comment]
将`TextView`用`FrameLayout`包裹，

然后设置`tab_indicator_width=WRAP_CONTENT`和`tab_indicator_content_index=0`,就可以实现指示器和文本等宽。

**Comment by angcyo** [comment]
`app:tabIndicatorFullWidth` 这个属性具体作用效果是什么？

你想在`tab_item_is_equ_width=true`的情况下， 排除某个Item不等宽？

**Comment by daiwenbo88** [comment]
多谢 刚刚试了用 FrameLayout 包裹  TextView 
在 tab_item_is_equ_width=true  情况下，实现 tab_indicator 和 tabText宽度一样  

有个问题就是这种情况下 选中的tab的字体颜色不会改变

`app:tabIndicatorFullWidth` 是Google  material:1.5.0 中TabLayout 新出样式

**Comment by angcyo** [comment]
我没用过系统的`Tablayout`， `app:tabIndicatorFullWidth` 具体是个啥样式能否描述清楚一下？

**Comment by angcyo** [comment]
> 

`3.2.3` 已修复。
