### ISSUE TITLE
横屏间隔点击跳转会出现ViewPager2偏移

### ISSUE THREAD

**Issue by Elex92** [angcyo/DslTabLayout#66]
如视频所示，为横屏布局，左侧有导航栏占位。右侧正常点Tab正常显示，但是间隔1个或2个点击就会出现偏移问

https://user-images.githubusercontent.com/16713043/167634680-cd7e9fc8-6966-47fc-bc9d-436d0f5c1210.mp4

题

**Comment by angcyo** [comment]
方便提供一个Demo源码？

**Comment by Elex92** [comment]
怎么发你啊？为弄个简单的工程发你，麻烦你了。

**Comment by Elex92** [comment]
大佬，我问题找到了，是我ConstraintLayout布局写的有点问题导致的，感谢！🙏
