### ISSUE TITLE
结合ViewPager2+Fragment 

### ISSUE THREAD

**Issue by bigmendan** [angcyo/DslTabLayout#68]
我在使用DslTabLayout +ViewPager2 +Fragment  使用时， 如果有三个Fragment, 当切换到第二个Fragement时，第2个和第3个的onCreateViewed都被触发，使用原生TabLayout时是没有这个问题的，请问怎么解决？

**Comment by angcyo** [comment]
参考: https://github.com/angcyo/DslTabLayout/issues/56
