### ISSUE TITLE
onSelectIndexChange可能引起tab点击切换ViewPager失效

### ISSUE THREAD

**Issue by asker517** [angcyo/DslTabLayout#7]
```kotlin
onSelectIndexChange
```
调用后,可能会导致tab点击切换viewPager失效?
源码:
```kotlin
tabLayoutConfig?.onSelectIndexChange?.invoke(fromIndex, selectList, reselect)
                    ?: _viewPagerDelegate?.onSetCurrentItem(fromIndex, toIndex)
```

**Comment by angcyo** [comment]
`DslTabLayout`强解耦`ViewPager`和`ViewPager2`, 所以库中是没有`VP`操作的, 需要使用者手动操作.

有2种方法可以关联控制`VP`:

1:通过设置`tabLayoutConfig`, 在回调`onSelectIndexChange`控制`VP`
2:调用`setupViewPager`方法, 设置`_viewPagerDelegate`实现`onSetCurrentItem`方法控制`VP`

**Comment by asker517** [comment]
@angcyo OK
