### ISSUE TITLE
多层嵌套问题？

### ISSUE THREAD

**Issue by SmallWinter** [angcyo/DslTabLayout#71]
感谢作者，就一个问题，多层嵌套滑动是否不支持？

**Comment by angcyo** [comment]
未测试

**Comment by SmallWinter** [comment]
> 未测试

我测试了一下，确实多层嵌套存在问题，无法正常工作；用的最新版本，Viewpager2

**Comment by SmallWinter** [comment]
补充一下：多层嵌套，只有最外层的生效，内层的无法生效。

**Comment by angcyo** [comment]
原生的`TabLayout`支持`ViewPager2`嵌套吗?

**Comment by SmallWinter** [comment]
不好意思，经过测试，tablayout+viewpager2也存在同样问题，看来是viewpager2特性导致，已经换回viewpager了，感谢！

**Comment by AversonCoder** [comment]
假定 ParentFragment(Tab + ViewPager2) + ChildFragment(Tab + ViewPager2) 的情况下。

使用该方案：[NestedScrollableHost](https://github.com/android/views-widgets-samples/blob/master/ViewPager2/app/src/main/java/androidx/viewpager2/integration/testapp/NestedScrollableHost.kt) 可解决多层嵌套连续滑动的情况。
