### ISSUE TITLE
初始状态

### ISSUE THREAD

**Issue by 79660095** [angcyo/DslTabLayout#72]
大佬弱弱的问一句，初次的时候 onSelectIndexChange，onSelectViewChange这两个事件是不是会默认执行1次，感觉我有一点没有理解，既然是回调事件，我都没有手动触发就在初始的时候执行了一次。这似乎不太符合逻辑。 当然默认有选中状态大多都会走一遍默认选中的回调事件大多数都常用。有时候我不想在初次的时候 就执行item事件里的内容当然我也可以自己定义标识，就是想问一下是会默认走一遍初始选中的执行了这个回调，还是有什么属性我没有关注到的

**Comment by angcyo** [comment]
可以使用 `fromUser` 判断.

**Comment by 79660095** [comment]
* @param fromUser 是否是用户产生的回调, 而非代码设置,用这个判断就不准吧，要是后续我有这个手动调用切换的需求那不是判断不到了，还是只能加标识 是不是初次调用。库功能真的是非常的棒。

**Comment by angcyo** [comment]
`com.angcyo.tablayout.DslTabLayout#setCurrentItem`

```
fun setCurrentItem(index: Int, notify: Boolean = true, fromUser: Boolean = false) {
  ...
}
```

手动调用此方法时, 可以指定`fromUser`.
