### ISSUE TITLE
怎么让文字不居中变大？

### ISSUE THREAD

**Issue by GuangNian10000** [angcyo/DslTabLayout#78]
tab_enable_gradient_text_size设置后文字是居中方大大，如何让文字保持底对齐？

**Comment by GuangNian10000** [comment]
解决方式1：动态改变边距

**Comment by angcyo** [comment]
将`TextView`放在`FrameLayout`中, 使用`Gravity.BOTTOM`.

**Comment by GuangNian10000** [comment]
> 将`TextView`放在`FrameLayout`中, 使用`Gravity.BOTTOM`. 然后文本也使用`android.widget.TextView#setGravity(Gravity.BOTTOM)`

感谢大佬
