### ISSUE TITLE
动态修改某一项item  

### ISSUE THREAD

**Issue by HeroBarry** [angcyo/DslTabLayout#81]
图片item和文字item一起使用的时候   初始化时都是文字item  选中到某项以后该项变成图片item
拜读源码没有发现重新设置的item项目的位置呢？有重新设置的地方么？
怎么解决？

**Comment by HeroBarry** [comment]
类似腾讯视频的tab

**Comment by HeroBarry** [comment]
![image](https://user-images.githubusercontent.com/7805207/222357867-6fb771a9-c3ee-4af3-ac38-181b4d88cb3a.png)

**Comment by HeroBarry** [comment]
![腾讯效果](https://user-images.githubusercontent.com/7805207/222357934-78d6a74b-7155-4c22-bbb5-89136270cb7a.png)

**Comment by angcyo** [comment]
改变View的可见性!

**Comment by HeroBarry** [comment]
明白  应该可以解决了
