### ISSUE TITLE
关于Item是否等宽 问题

### ISSUE THREAD

**Issue by Android-pengbo** [angcyo/DslTabLayout#87]
你好，我觉这个等宽问题 ,   当前的item 数量超过 当前屏幕的宽度就让他可以滑动，没有超过的话就等分，就类似于Android 原生的TabLayout 的 TabMode  auto属性一样。也有可能是已经有了相应的api 我没找到，还望指点一下。

**Comment by angcyo** [comment]
`tab_item_auto_equ_width`
