### ISSUE TITLE
如何修改某个Item的文本？

### ISSUE THREAD

**Issue by chen-fuhai** [angcyo/DslTabLayout#95]

**Comment by chen-fuhai** [comment]
创建Item，如何修改文本，TabLayout有提供

**Comment by angcyo** [comment]
先指定控件的id, 这个id在同一个xml文件中可以重复使用. ide会爆红, 但是运行不会报错.
然后通过`android.view.ViewGroup#getChildAt`
再通过`android.view.View#findViewById`获取指定控件.
