### ISSUE TITLE
请问能自定义TextView的Scale动画么

### ISSUE THREAD

**Issue by traywangjun** [angcyo/DslTabLayout#96]
![image](https://github.com/angcyo/DslTabLayout/assets/11623476/855f243c-1fb6-4374-9f78-633898a955b6)
我这个需要从文字的左下角开始放大，demo中是以文字中心放大，大佬提供个思路

**Comment by angcyo** [comment]
实现一个自己的`com.angcyo.tablayout.DslTabLayoutConfig#tabGradientCallback`回调.

**Comment by traywangjun** [comment]
根据大佬的提示改了Scale动画但是 初始化的时候tabIndicator位置不对然后TextView的位置也不对，点击一下才可以
![image](https://github.com/angcyo/DslTabLayout/assets/11623476/5a4ff901-d08e-464f-bd67-cee74e3689f6)
![image](https://github.com/angcyo/DslTabLayout/assets/11623476/e16ec718-ae92-4bd2-84a3-6c5a3f3503bc)

**Comment by angcyo** [comment]
初始化完成之后调用`com.angcyo.tablayout.DslTabLayout#updateTabLayout`

**Comment by traywangjun** [comment]
还是没用，我移除所有item然后动态添加第一个也是无效的，添加第二个就可以
