### ISSUE TITLE
动态配置数据，默认全不选中无效。还是选中上次选择的下标

### ISSUE THREAD

**Issue by MhuiHugh** [angcyo/DslTabLayout#98]
` bodyBinding.dslTablayout.apply {
                removeAllViews()
                viewModel.labelList?.forEach {
                    val textView = TextView(context)
                    textView.text = it.labelName
                    textView.gravity = Gravity.CENTER
                    addView(textView)
                    textView.invalidate()
                }
                //tabDefaultIndex = -1
                //setCurrentItem(-1, false, false)
                ///dslSelector.selectorAll(false, true, false)
            }
            bodyBinding.dslTablayout.dslSelector.selectorAll(false, true, false)`

**Comment by MhuiHugh** [comment]
2个设置方法都无效   bodyBinding.dslTablayout.setCurrentItem(-1,true,false)  
   bodyBinding.dslTablayout.dslSelector.selectorAll(false, true, false)

**Comment by angcyo** [comment]
需要调用一次`com.angcyo.tablayout.DslTabLayout#updateTabLayout`
